// <auto-generated />
using System;
using System.Collections.Generic;
using LeadDirecter.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeadDirecter.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251108160001_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeadDirecter.Data.Entities.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("CampaignMacros")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FunnelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TargetCountry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrafficBuyerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TrafficSourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("LeadDirecter.Data.Entities.DestinationCrmConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthConfig")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CooperationStartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CrmName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorIdentifier")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LeadRegistrationBodyTemplate")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LeadRegistrationContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadRegistrationEndpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadRegistrationHeaders")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LeadRegistrationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadRetrievalBodyTemplate")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LeadRetrievalContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadsRegistrationQueryParams")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LeadsRetrievalEndpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadsRetrievalHeaders")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LeadsRetrievalMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadsRetrievalQueryParams")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseMappingProperty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("DestinationCrmConfigurations");
                });

            modelBuilder.Entity("LeadDirecter.Data.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid");

                    b.Property<string>("CampaignMacros")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CountryCodeIso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DestinationCrmConfigurationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FtdAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsFtd")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSentSuccessfully")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerifiedFtd")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LeadIdInExternalCrm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("DestinationCrmConfigurationId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("LeadDirecter.Data.Entities.DestinationCrmConfiguration", b =>
                {
                    b.HasOne("LeadDirecter.Data.Entities.Campaign", "Campaign")
                        .WithMany("DestinationCrmConfigurations")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Campaign");
                });

            modelBuilder.Entity("LeadDirecter.Data.Entities.Lead", b =>
                {
                    b.HasOne("LeadDirecter.Data.Entities.Campaign", null)
                        .WithMany("Leads")
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LeadDirecter.Data.Entities.DestinationCrmConfiguration", null)
                        .WithMany("Leads")
                        .HasForeignKey("DestinationCrmConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LeadDirecter.Data.Entities.Campaign", b =>
                {
                    b.Navigation("DestinationCrmConfigurations");

                    b.Navigation("Leads");
                });

            modelBuilder.Entity("LeadDirecter.Data.Entities.DestinationCrmConfiguration", b =>
                {
                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
